import {
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  Bold,
  BookOpen,
  BookOpenText,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleCheck,
  CircleDollarSign,
  CircleX,
  Clipboard,
  Code,
  CodeXml,
  Copy,
  Edit,
  Ellipsis,
  Eye,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  FolderPlus,
  Heart,
  House,
  Image,
  Info,
  Italic,
  LayoutDashboard,
  Layers,
  Layers2,
  Lightbulb,
  LightbulbOff,
  Loader2,
  LoaderCircle,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Monitor,
  Moon,
  MoreVertical,
  MoveRight,
  Palette,
  PanelLeft,
  Plus,
  Puzzle,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  Smartphone,
  Sparkles,
  SquareLibrary,
  Star,
  Sun,
  Tablet,
  Terminal,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignStart,
  Trash2,
  TriangleAlert,
  Underline,
  User,
  Users,
  X,
  Zap,
  type LucideIconData,
  Circle,
  Inbox,
} from 'lucide-angular';

export const ZARD_ICONS = {
  house: House,
  settings: Settings,
  user: User,
  search: Search,
  bell: Bell,
  mail: Mail,
  calendar: Calendar,
  'log-out': LogOut,
  'panel-left': PanelLeft,
  bold: Bold,
  inbox: Inbox,
  italic: Italic,
  underline: Underline,
  'text-align-center': TextAlignCenter,
  'text-align-end': TextAlignEnd,
  'text-align-start': TextAlignStart,
  check: Check,
  'check-check': CheckCheck,
  x: X,
  info: Info,
  'triangle-alert': TriangleAlert,
  circle: Circle,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'circle-dollar-sign': CircleDollarSign,
  ban: Ban,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'move-right': MoveRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  file: File,
  'file-text': FileText,
  filter: Filter,
  'layout-dashboard': LayoutDashboard,
  'loader-circle': LoaderCircle,
  'loader-2': Loader2,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'more-vertical': MoreVertical,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  save: Save,
  send: Send,
  copy: Copy,
  eye: Eye,
  ellipsis: Ellipsis,
  terminal: Terminal,
  clipboard: Clipboard,
  moon: Moon,
  sun: Sun,
  lightbulb: Lightbulb,
  'lightbulb-off': LightbulbOff,
  palette: Palette,
  sparkles: Sparkles,
  heart: Heart,
  star: Star,
  zap: Zap,
  flag: Flag,
  shield: Shield,
  puzzle: Puzzle,
  layers: Layers,
  'layers-2': Layers2,
  'square-library': SquareLibrary,
  code: Code,
  'code-xml': CodeXml,
  'book-open': BookOpen,
  'book-open-text': BookOpenText,
  users: Users,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  edit: Edit,
  image: Image,
  plus: Plus,
  'trash-2': Trash2,
} as const satisfies Record<string, LucideIconData>;

export declare type ZardIcon = keyof typeof ZARD_ICONS | LucideIconData;
